language: cpp

sudo: required

cache: ccache

dist: xenial

services:
  - docker

matrix:
  include:
    - env: VERSION=8 BITS=64
      compiler: gcc
      os: linux
    - env: VERSION=8 BITS=32
      compiler: gcc
      os: linux
    - env: VERSION=7 BITS=32
      compiler: gcc
      os: linux
    - env: VERSION=3.8 BITS=32
      compiler: clang
      os: linux
    - name: Fedora 31 - Docker
      env: SKIP_TRAVIS_BASH_SCRIPT=1
      script:
        - docker build --tag pcsx2-fedora --file docker/fedora.Dockerfile .
        - docker run --rm -it pcsx2-fedora ./build.sh --gtk3
    - name: Debian 10 (Buster) - Docker
      env: SKIP_TRAVIS_BASH_SCRIPT=1
      script:
        - docker build --tag pcsx2-debian --file docker/debian.Dockerfile .
        - docker run --rm -it pcsx2-debian ./build.sh --gtk3
    - name: Ubuntu 18.04 (Bionic) - Docker
      env: SKIP_TRAVIS_BASH_SCRIPT=1
      script:
        - docker build --tag pcsx2-ubuntu --file docker/ubuntu.Dockerfile .
        - docker run --rm -it pcsx2-ubuntu ./build.sh --gtk3

before_install:
  - ./travis.sh before_install

before_script:
  - ./travis.sh before_script

script:
  - ./travis.sh script

after_success:
  - ./travis.sh after_success
